//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKM.DAO.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quyen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Quyen()
        {
            this.NhomQuyenQuyens = new HashSet<NhomQuyenQuyen>();
        }
    
        public int ID { get; set; }
        public Nullable<int> KhoaChaID { get; set; }
        public string MaQuyen { get; set; }
        public string TenQuyen { get; set; }
        public bool NhanQuyen { get; set; }
        public string TenHienThi { get; set; }
        public string Controller { get; set; }
        public string IconPath { get; set; }
        public string GhiChu { get; set; }
        public string Action { get; set; }
        public string FontAwesome { get; set; }
        public bool IsMenu { get; set; }
        public Nullable<byte> PhanHe { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> NguoiTaoID { get; set; }
        public Nullable<int> NguoiCapNhatID { get; set; }
        public string NguoiCapNhat { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> ThuTu { get; set; }
        public bool TrangThai { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhomQuyenQuyen> NhomQuyenQuyens { get; set; }
    }
}
