//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKM.DAO.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TKMReportsEntities : DbContext
    {
        public TKMReportsEntities()
            : base("name=TKMReportsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AffectedItem> AffectedItems { get; set; }
        public virtual DbSet<AlertGroup> AlertGroups { get; set; }
        public virtual DbSet<HeThongThamSo> HeThongThamSoes { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<NhatKyHeThong> NhatKyHeThongs { get; set; }
        public virtual DbSet<NhomNguoiDung> NhomNguoiDungs { get; set; }
        public virtual DbSet<NhomQuyen> NhomQuyens { get; set; }
        public virtual DbSet<NhomQuyenQuyen> NhomQuyenQuyens { get; set; }
        public virtual DbSet<Quyen> Quyens { get; set; }
        public virtual DbSet<ScannedItem> ScannedItems { get; set; }
        public virtual DbSet<ThongBao> ThongBaos { get; set; }
        public virtual DbSet<ThongBaoAttach> ThongBaoAttaches { get; set; }
        public virtual DbSet<TuDienVietHoa> TuDienVietHoas { get; set; }
        public virtual DbSet<Website> Websites { get; set; }
        public virtual DbSet<WebsiteItem> WebsiteItems { get; set; }
        public virtual DbSet<WebsiteScan> WebsiteScans { get; set; }
    
        public virtual ObjectResult<CountHostsByGroup_Result> CountHostsByGroup(string p_listGroup, string p_trangThai, Nullable<System.DateTime> p_tuNgay, Nullable<System.DateTime> p_denNgay, Nullable<int> p_pageIndex, Nullable<int> p_pageSize, string p_columnName, string p_orderBy)
        {
            var p_listGroupParameter = p_listGroup != null ?
                new ObjectParameter("p_listGroup", p_listGroup) :
                new ObjectParameter("p_listGroup", typeof(string));
    
            var p_trangThaiParameter = p_trangThai != null ?
                new ObjectParameter("p_trangThai", p_trangThai) :
                new ObjectParameter("p_trangThai", typeof(string));
    
            var p_tuNgayParameter = p_tuNgay.HasValue ?
                new ObjectParameter("p_tuNgay", p_tuNgay) :
                new ObjectParameter("p_tuNgay", typeof(System.DateTime));
    
            var p_denNgayParameter = p_denNgay.HasValue ?
                new ObjectParameter("p_denNgay", p_denNgay) :
                new ObjectParameter("p_denNgay", typeof(System.DateTime));
    
            var p_pageIndexParameter = p_pageIndex.HasValue ?
                new ObjectParameter("p_pageIndex", p_pageIndex) :
                new ObjectParameter("p_pageIndex", typeof(int));
    
            var p_pageSizeParameter = p_pageSize.HasValue ?
                new ObjectParameter("p_pageSize", p_pageSize) :
                new ObjectParameter("p_pageSize", typeof(int));
    
            var p_columnNameParameter = p_columnName != null ?
                new ObjectParameter("p_columnName", p_columnName) :
                new ObjectParameter("p_columnName", typeof(string));
    
            var p_orderByParameter = p_orderBy != null ?
                new ObjectParameter("p_orderBy", p_orderBy) :
                new ObjectParameter("p_orderBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CountHostsByGroup_Result>("CountHostsByGroup", p_listGroupParameter, p_trangThaiParameter, p_tuNgayParameter, p_denNgayParameter, p_pageIndexParameter, p_pageSizeParameter, p_columnNameParameter, p_orderByParameter);
        }
    
        public virtual ObjectResult<CountProblemBySeverity_Result> CountProblemBySeverity(string p_listGroup, string p_trangThai, string p_groupBy, Nullable<System.DateTime> p_tuNgay, Nullable<System.DateTime> p_denNgay, Nullable<int> p_pageIndex, Nullable<int> p_pageSize, string p_columnName, string p_orderBy)
        {
            var p_listGroupParameter = p_listGroup != null ?
                new ObjectParameter("p_listGroup", p_listGroup) :
                new ObjectParameter("p_listGroup", typeof(string));
    
            var p_trangThaiParameter = p_trangThai != null ?
                new ObjectParameter("p_trangThai", p_trangThai) :
                new ObjectParameter("p_trangThai", typeof(string));
    
            var p_groupByParameter = p_groupBy != null ?
                new ObjectParameter("p_groupBy", p_groupBy) :
                new ObjectParameter("p_groupBy", typeof(string));
    
            var p_tuNgayParameter = p_tuNgay.HasValue ?
                new ObjectParameter("p_tuNgay", p_tuNgay) :
                new ObjectParameter("p_tuNgay", typeof(System.DateTime));
    
            var p_denNgayParameter = p_denNgay.HasValue ?
                new ObjectParameter("p_denNgay", p_denNgay) :
                new ObjectParameter("p_denNgay", typeof(System.DateTime));
    
            var p_pageIndexParameter = p_pageIndex.HasValue ?
                new ObjectParameter("p_pageIndex", p_pageIndex) :
                new ObjectParameter("p_pageIndex", typeof(int));
    
            var p_pageSizeParameter = p_pageSize.HasValue ?
                new ObjectParameter("p_pageSize", p_pageSize) :
                new ObjectParameter("p_pageSize", typeof(int));
    
            var p_columnNameParameter = p_columnName != null ?
                new ObjectParameter("p_columnName", p_columnName) :
                new ObjectParameter("p_columnName", typeof(string));
    
            var p_orderByParameter = p_orderBy != null ?
                new ObjectParameter("p_orderBy", p_orderBy) :
                new ObjectParameter("p_orderBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CountProblemBySeverity_Result>("CountProblemBySeverity", p_listGroupParameter, p_trangThaiParameter, p_groupByParameter, p_tuNgayParameter, p_denNgayParameter, p_pageIndexParameter, p_pageSizeParameter, p_columnNameParameter, p_orderByParameter);
        }
    
        public virtual ObjectResult<CountProblemByStatus_Result> CountProblemByStatus(string p_listGroup, string p_trangThai, string p_groupBy, Nullable<System.DateTime> p_tuNgay, Nullable<System.DateTime> p_denNgay, Nullable<int> p_pageIndex, Nullable<int> p_pageSize, string p_columnName, string p_orderBy)
        {
            var p_listGroupParameter = p_listGroup != null ?
                new ObjectParameter("p_listGroup", p_listGroup) :
                new ObjectParameter("p_listGroup", typeof(string));
    
            var p_trangThaiParameter = p_trangThai != null ?
                new ObjectParameter("p_trangThai", p_trangThai) :
                new ObjectParameter("p_trangThai", typeof(string));
    
            var p_groupByParameter = p_groupBy != null ?
                new ObjectParameter("p_groupBy", p_groupBy) :
                new ObjectParameter("p_groupBy", typeof(string));
    
            var p_tuNgayParameter = p_tuNgay.HasValue ?
                new ObjectParameter("p_tuNgay", p_tuNgay) :
                new ObjectParameter("p_tuNgay", typeof(System.DateTime));
    
            var p_denNgayParameter = p_denNgay.HasValue ?
                new ObjectParameter("p_denNgay", p_denNgay) :
                new ObjectParameter("p_denNgay", typeof(System.DateTime));
    
            var p_pageIndexParameter = p_pageIndex.HasValue ?
                new ObjectParameter("p_pageIndex", p_pageIndex) :
                new ObjectParameter("p_pageIndex", typeof(int));
    
            var p_pageSizeParameter = p_pageSize.HasValue ?
                new ObjectParameter("p_pageSize", p_pageSize) :
                new ObjectParameter("p_pageSize", typeof(int));
    
            var p_columnNameParameter = p_columnName != null ?
                new ObjectParameter("p_columnName", p_columnName) :
                new ObjectParameter("p_columnName", typeof(string));
    
            var p_orderByParameter = p_orderBy != null ?
                new ObjectParameter("p_orderBy", p_orderBy) :
                new ObjectParameter("p_orderBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CountProblemByStatus_Result>("CountProblemByStatus", p_listGroupParameter, p_trangThaiParameter, p_groupByParameter, p_tuNgayParameter, p_denNgayParameter, p_pageIndexParameter, p_pageSizeParameter, p_columnNameParameter, p_orderByParameter);
        }
    
        public virtual ObjectResult<GetFilterHieuNang_Result> GetFilterHieuNang(string p_groupTime)
        {
            var p_groupTimeParameter = p_groupTime != null ?
                new ObjectParameter("p_groupTime", p_groupTime) :
                new ObjectParameter("p_groupTime", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFilterHieuNang_Result>("GetFilterHieuNang", p_groupTimeParameter);
        }
    
        public virtual ObjectResult<GetNhomThietBi_Result> GetNhomThietBi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetNhomThietBi_Result>("GetNhomThietBi");
        }
    
        public virtual ObjectResult<GetProblemDetail_Result> GetProblemDetail(string p_listGroup, string p_trangThai, string p_groupBy, Nullable<int> p_capDo, Nullable<System.DateTime> p_tuNgay, Nullable<System.DateTime> p_denNgay, Nullable<int> p_pageIndex, Nullable<int> p_pageSize, string p_columnName, string p_orderBy)
        {
            var p_listGroupParameter = p_listGroup != null ?
                new ObjectParameter("p_listGroup", p_listGroup) :
                new ObjectParameter("p_listGroup", typeof(string));
    
            var p_trangThaiParameter = p_trangThai != null ?
                new ObjectParameter("p_trangThai", p_trangThai) :
                new ObjectParameter("p_trangThai", typeof(string));
    
            var p_groupByParameter = p_groupBy != null ?
                new ObjectParameter("p_groupBy", p_groupBy) :
                new ObjectParameter("p_groupBy", typeof(string));
    
            var p_capDoParameter = p_capDo.HasValue ?
                new ObjectParameter("p_capDo", p_capDo) :
                new ObjectParameter("p_capDo", typeof(int));
    
            var p_tuNgayParameter = p_tuNgay.HasValue ?
                new ObjectParameter("p_tuNgay", p_tuNgay) :
                new ObjectParameter("p_tuNgay", typeof(System.DateTime));
    
            var p_denNgayParameter = p_denNgay.HasValue ?
                new ObjectParameter("p_denNgay", p_denNgay) :
                new ObjectParameter("p_denNgay", typeof(System.DateTime));
    
            var p_pageIndexParameter = p_pageIndex.HasValue ?
                new ObjectParameter("p_pageIndex", p_pageIndex) :
                new ObjectParameter("p_pageIndex", typeof(int));
    
            var p_pageSizeParameter = p_pageSize.HasValue ?
                new ObjectParameter("p_pageSize", p_pageSize) :
                new ObjectParameter("p_pageSize", typeof(int));
    
            var p_columnNameParameter = p_columnName != null ?
                new ObjectParameter("p_columnName", p_columnName) :
                new ObjectParameter("p_columnName", typeof(string));
    
            var p_orderByParameter = p_orderBy != null ?
                new ObjectParameter("p_orderBy", p_orderBy) :
                new ObjectParameter("p_orderBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProblemDetail_Result>("GetProblemDetail", p_listGroupParameter, p_trangThaiParameter, p_groupByParameter, p_capDoParameter, p_tuNgayParameter, p_denNgayParameter, p_pageIndexParameter, p_pageSizeParameter, p_columnNameParameter, p_orderByParameter);
        }
    
        public virtual ObjectResult<HieuNangNhomThietBi_Result> HieuNangNhomThietBi(string p_listGroup, string p_listHost, string p_groupBy, string p_groupTime, string p_keyType, Nullable<int> p_getDetail, Nullable<System.DateTime> p_tuNgay, Nullable<System.DateTime> p_denNgay, Nullable<int> p_pageIndex, Nullable<int> p_pageSize, string p_columnName, string p_orderBy)
        {
            var p_listGroupParameter = p_listGroup != null ?
                new ObjectParameter("p_listGroup", p_listGroup) :
                new ObjectParameter("p_listGroup", typeof(string));
    
            var p_listHostParameter = p_listHost != null ?
                new ObjectParameter("p_listHost", p_listHost) :
                new ObjectParameter("p_listHost", typeof(string));
    
            var p_groupByParameter = p_groupBy != null ?
                new ObjectParameter("p_groupBy", p_groupBy) :
                new ObjectParameter("p_groupBy", typeof(string));
    
            var p_groupTimeParameter = p_groupTime != null ?
                new ObjectParameter("p_groupTime", p_groupTime) :
                new ObjectParameter("p_groupTime", typeof(string));
    
            var p_keyTypeParameter = p_keyType != null ?
                new ObjectParameter("p_keyType", p_keyType) :
                new ObjectParameter("p_keyType", typeof(string));
    
            var p_getDetailParameter = p_getDetail.HasValue ?
                new ObjectParameter("p_getDetail", p_getDetail) :
                new ObjectParameter("p_getDetail", typeof(int));
    
            var p_tuNgayParameter = p_tuNgay.HasValue ?
                new ObjectParameter("p_tuNgay", p_tuNgay) :
                new ObjectParameter("p_tuNgay", typeof(System.DateTime));
    
            var p_denNgayParameter = p_denNgay.HasValue ?
                new ObjectParameter("p_denNgay", p_denNgay) :
                new ObjectParameter("p_denNgay", typeof(System.DateTime));
    
            var p_pageIndexParameter = p_pageIndex.HasValue ?
                new ObjectParameter("p_pageIndex", p_pageIndex) :
                new ObjectParameter("p_pageIndex", typeof(int));
    
            var p_pageSizeParameter = p_pageSize.HasValue ?
                new ObjectParameter("p_pageSize", p_pageSize) :
                new ObjectParameter("p_pageSize", typeof(int));
    
            var p_columnNameParameter = p_columnName != null ?
                new ObjectParameter("p_columnName", p_columnName) :
                new ObjectParameter("p_columnName", typeof(string));
    
            var p_orderByParameter = p_orderBy != null ?
                new ObjectParameter("p_orderBy", p_orderBy) :
                new ObjectParameter("p_orderBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HieuNangNhomThietBi_Result>("HieuNangNhomThietBi", p_listGroupParameter, p_listHostParameter, p_groupByParameter, p_groupTimeParameter, p_keyTypeParameter, p_getDetailParameter, p_tuNgayParameter, p_denNgayParameter, p_pageIndexParameter, p_pageSizeParameter, p_columnNameParameter, p_orderByParameter);
        }
    
        public virtual ObjectResult<HostsByGroup_Result> HostsByGroup(string p_listGroup, string p_hostname, Nullable<int> p_pageIndex, Nullable<int> p_pageSize, string p_columnName, string p_orderBy)
        {
            var p_listGroupParameter = p_listGroup != null ?
                new ObjectParameter("p_listGroup", p_listGroup) :
                new ObjectParameter("p_listGroup", typeof(string));
    
            var p_hostnameParameter = p_hostname != null ?
                new ObjectParameter("p_hostname", p_hostname) :
                new ObjectParameter("p_hostname", typeof(string));
    
            var p_pageIndexParameter = p_pageIndex.HasValue ?
                new ObjectParameter("p_pageIndex", p_pageIndex) :
                new ObjectParameter("p_pageIndex", typeof(int));
    
            var p_pageSizeParameter = p_pageSize.HasValue ?
                new ObjectParameter("p_pageSize", p_pageSize) :
                new ObjectParameter("p_pageSize", typeof(int));
    
            var p_columnNameParameter = p_columnName != null ?
                new ObjectParameter("p_columnName", p_columnName) :
                new ObjectParameter("p_columnName", typeof(string));
    
            var p_orderByParameter = p_orderBy != null ?
                new ObjectParameter("p_orderBy", p_orderBy) :
                new ObjectParameter("p_orderBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HostsByGroup_Result>("HostsByGroup", p_listGroupParameter, p_hostnameParameter, p_pageIndexParameter, p_pageSizeParameter, p_columnNameParameter, p_orderByParameter);
        }
    
        public virtual ObjectResult<DeXuatNhomThietBi_Result> DeXuatNhomThietBi(string p_listGroup, string p_listHost, string p_groupBy, string p_groupTime, string p_keyType, Nullable<int> p_getDetail, Nullable<System.DateTime> p_tuNgay, Nullable<System.DateTime> p_denNgay, Nullable<int> p_pageIndex, Nullable<int> p_pageSize, string p_columnName, string p_orderBy)
        {
            var p_listGroupParameter = p_listGroup != null ?
                new ObjectParameter("p_listGroup", p_listGroup) :
                new ObjectParameter("p_listGroup", typeof(string));
    
            var p_listHostParameter = p_listHost != null ?
                new ObjectParameter("p_listHost", p_listHost) :
                new ObjectParameter("p_listHost", typeof(string));
    
            var p_groupByParameter = p_groupBy != null ?
                new ObjectParameter("p_groupBy", p_groupBy) :
                new ObjectParameter("p_groupBy", typeof(string));
    
            var p_groupTimeParameter = p_groupTime != null ?
                new ObjectParameter("p_groupTime", p_groupTime) :
                new ObjectParameter("p_groupTime", typeof(string));
    
            var p_keyTypeParameter = p_keyType != null ?
                new ObjectParameter("p_keyType", p_keyType) :
                new ObjectParameter("p_keyType", typeof(string));
    
            var p_getDetailParameter = p_getDetail.HasValue ?
                new ObjectParameter("p_getDetail", p_getDetail) :
                new ObjectParameter("p_getDetail", typeof(int));
    
            var p_tuNgayParameter = p_tuNgay.HasValue ?
                new ObjectParameter("p_tuNgay", p_tuNgay) :
                new ObjectParameter("p_tuNgay", typeof(System.DateTime));
    
            var p_denNgayParameter = p_denNgay.HasValue ?
                new ObjectParameter("p_denNgay", p_denNgay) :
                new ObjectParameter("p_denNgay", typeof(System.DateTime));
    
            var p_pageIndexParameter = p_pageIndex.HasValue ?
                new ObjectParameter("p_pageIndex", p_pageIndex) :
                new ObjectParameter("p_pageIndex", typeof(int));
    
            var p_pageSizeParameter = p_pageSize.HasValue ?
                new ObjectParameter("p_pageSize", p_pageSize) :
                new ObjectParameter("p_pageSize", typeof(int));
    
            var p_columnNameParameter = p_columnName != null ?
                new ObjectParameter("p_columnName", p_columnName) :
                new ObjectParameter("p_columnName", typeof(string));
    
            var p_orderByParameter = p_orderBy != null ?
                new ObjectParameter("p_orderBy", p_orderBy) :
                new ObjectParameter("p_orderBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DeXuatNhomThietBi_Result>("DeXuatNhomThietBi", p_listGroupParameter, p_listHostParameter, p_groupByParameter, p_groupTimeParameter, p_keyTypeParameter, p_getDetailParameter, p_tuNgayParameter, p_denNgayParameter, p_pageIndexParameter, p_pageSizeParameter, p_columnNameParameter, p_orderByParameter);
        }
    }
}
