//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKM.DAO.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_AffectedItem
    {
        public int ID { get; set; }
        public int WebsiteID { get; set; }
        public int WebiteScanID { get; set; }
        public int AlertGroupID { get; set; }
        public string ScanPath { get; set; }
        public string Detail { get; set; }
        public string SourceCode { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> Status { get; set; }
        public string AlertName { get; set; }
        public string AlertNameTrans { get; set; }
        public string Severity { get; set; }
        public string SeverityNum { get; set; }
        public string AlertVariants { get; set; }
    }
}
