//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKM.DAO.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Website
    {
        public int ID { get; set; }
        public string StartURL { get; set; }
        public string Host { get; set; }
        public string Responsive { get; set; }
        public string ServerOS { get; set; }
        public string ServerInformation { get; set; }
        public string ServerTechnologies { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> cLuotQuet { get; set; }
        public Nullable<int> cTongNguyCo { get; set; }
        public Nullable<int> cTongNguyCoCao { get; set; }
        public Nullable<int> cTongNguyCoTB { get; set; }
        public Nullable<int> cTongNguyCoThap { get; set; }
        public Nullable<int> cTongNguyCoInfor { get; set; }
        public Nullable<int> cTongItem { get; set; }
        public Nullable<System.DateTime> LastScan { get; set; }
    }
}
