//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKM.DAO.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebsiteScan
    {
        public int ID { get; set; }
        public int WebsiteID { get; set; }
        public System.DateTime StartTime { get; set; }
        public string ScanTime { get; set; }
        public string ThreatLevel { get; set; }
        public Nullable<int> TotalSecond { get; set; }
        public Nullable<int> TotalItemScan { get; set; }
        public Nullable<int> TotalAlertFound { get; set; }
        public Nullable<int> HighAlert { get; set; }
        public Nullable<int> MediumAlert { get; set; }
        public Nullable<int> LowAlert { get; set; }
        public Nullable<int> InforAlert { get; set; }
        public string ScanProfile { get; set; }
        public string ScanStatus { get; set; }
        public string RootReportUrl { get; set; }
        public string NewReportUrl { get; set; }
        public string ReportHTML { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
